{{- if eq .Values.global.ory.oathkeeper.maester.mode "controller" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oathkeeper-maester.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "oathkeeper-maester.labels" . | nindent 4 }}
    {{- with .Values.deployment.extraLabels }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: {{ include "oathkeeper-maester.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: {{ include "oathkeeper-maester.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.deployment.podMetadata.labels }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.deployment.podMetadata.annotations }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.deployment.annotations }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --metrics-addr=0.0.0.0:8080
            - controller
            - --rulesConfigmapName={{ include "oathkeeper-maester.getCM" . }}
            {{- if .Values.rulesConfigmapNamespace }}
            - --rulesConfigmapNamespace={{ .Values.rulesConfigmapNamespace }}
            {{- else }}
            - --rulesConfigmapNamespace={{ .Release.Namespace }}
            {{- end }}
            {{- if .Values.rulesFileName }}
            - --rulesFileName={{ .Values.rulesFileName }}
            {{- end }}
          env:
            {{- if .Values.singleNamespaceMode }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            {{- end }}
            {{- with .Values.deployment.envs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{- if .Values.deployment.securityContext }}
          securityContext:
            {{- toYaml .Values.deployment.securityContext | nindent 12 }}
          {{- end }}
      serviceAccountName: {{ include "oathkeeper-maester.fullname" . }}-account
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 10
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      nodeSelector:
      {{- with .Values.deployment.nodeSelector }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- tpl (toYaml .) $ | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (toYaml .) $ | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.dnsConfig }}
      dnsConfig:
        {{- tpl (toYaml .) $ | nindent 8 }}
    {{- end }}
{{- end }}
